
class NotFoundError(Exception):
    pass


class ValidationError(Exception):
    pass
